[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_18']

[phases.install]
cmds = [
    'cd backend',
    'composer install --no-dev --optimize-autoloader'
]

[phases.build]
cmds = [
    'cd backend',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'cd backend && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT'
